set(include_files_h5geo
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5base.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5basecontainerimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5baseimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5baseobjectimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5core_enum.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5core_enum_operators.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5core_enum_string.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5core_misc.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5core_sr_settings.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5devcurveimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5deviation.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5easyhull.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5interpolation.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5logcurveimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5seiscontainerimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5seisimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5sort.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5mapcontainerimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5mapimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5wellcontainerimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5wellimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5pointsimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5polyfit.h

  ${CMAKE_SOURCE_DIR}/include/h5geo/h5basecontainer.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5baseobject.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5core.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5devcurve.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5logcurve.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5seis.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5seiscontainer.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5mapcontainer.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5map.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5well.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5wellcontainer.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5points.h
  )
