set(include_files
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5base.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5basecontainer.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5basecontainerimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5baseimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5baseobject.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5baseobjectimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5core_enum_operators.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5core_enum.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5devcurveimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5deviation.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5easyhull.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5find.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5logcurveimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5segy_headers.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5seiscontainerimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5seisimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5sort.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5surfcontainerimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5surfimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5wellcontainerimpl.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/misc/h5wellimpl.h

  ${CMAKE_SOURCE_DIR}/include/h5geo/h5core.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5devcurve.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5logcurve.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5seis.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5seiscontainer.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5surfcontainer.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5surf.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5well.h
  ${CMAKE_SOURCE_DIR}/include/h5geo/h5wellcontainer.h
  )